### ISSUE TITLE
Work in progress or unmaintained?

### ISSUE THREAD

**Issue by holys** [guileen/nemesis#1]
it seems  that the project has stopped with unfinished features

**Comment by guileen** [comment]
Thanks for watching. 

Sometime I got some idea, I will put it on github, but I didn't have enough time to implement it, unless I really need it in my work. Maybe it is not a good habit make people confuse.

For some reason, the project I plan to use "nemesis" as main proxy server has move to nginx. But if the community like the project, I will work on it again, current I am a little worry about the performance vs nginx.
